spring:
  application:
    name: images-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  minio:
    endpoint: ${MINIO_ENDPOINT:http://minio:9000}
    root-user: ${MINIO_ROOT_USER:minioadmin}
    root-password: ${MINIO_ROOT_PASSWORD:minioadmin}
    bucket: ${MINIO_BUCKET:images}