services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8090:8090"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_URL_HOST: alibabos-db-0dkrh4
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: postgres
      KC_HTTP_PORT: 8090
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
    command: ['start']
    # command: ["start", "--optimized"]
