
# ATTENTION CREDENTIAL HARD CODE, A CHANGER
spring.application.name=builder-service
spring.data.mongodb.uri=mongodb+srv://alibabos:5la2OoJUthZhRlXr@cluster0.8qc3a.mongodb.net/?appName=Cluster0
server.port=8080