spring.application.name=builder-service
spring.data.mongodb.uri=mongodb+srv://alibabos:MbvGKGgoXQS5syO8@cluster0.8qc3a.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=builder-service
server.port=8081