name: Eureka Server CI/CD

on:
  push:
    paths:
      - 'backend/eureka-server/**'
      - '.github/workflows/eureka-ci.yml'

defaults:
  run:
    working-directory: backend/eureka-server

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spotless Lint
        run: mvn spotless:check

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean verify

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: eureka-test-reports
          path: ./target/surefire-reports/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Load kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy Eureka
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
