name: Eureka Server CI/CD

on:
  push:
    paths:
      - 'backend/eureka-server/**'
      - '.github/workflows/eureka-ci.yml'

defaults:
  run:
    working-directory: backend/eureka-server

jobs:
  build-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spotless Lint
        run: mvn spotless:check

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test
        run: mvn -B clean verify

      - name: Build Docker image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:$TAG .
          docker tag ${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:$TAG ${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:latest

      - name: Login DockerHub
        run: |
          echo "${{ secrets.EUREKA_DOCKER_TOKEN }}" \
          | docker login -u "${{ secrets.EUREKA_DOCKER_USER }}" --password-stdin

      - name: Push Docker image
        run: |
          TAG=${GITHUB_SHA::7}
          docker push ${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:$TAG
          docker push ${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:latest

  deploy:
    needs: build-test-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Load kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Ensure manifests exist
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Deploy to Kubernetes
        run: |
          TAG=${GITHUB_SHA::7}
          kubectl set image deployment/eureka-server \
            eureka-server=${{ secrets.EUREKA_DOCKER_USER }}/eureka-server:$TAG
          kubectl rollout status deployment/eureka-server
          kubectl delete pods -l app=eureka-server
          kubectl rollout status deployment/eureka-server
